[pytest]
addopts = --tb=short -q
log_cli = true
log_cli_level = WARNING
log_cli_format = %(message)s
log_level = WARNING
filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
    ignore::pytest.PytestWarning

markers =
    signIn: sign in tests
    signIn_1: sign in test variant 1
    signIn_2: sign in test variant 2
    settings: settings tests
    settings_1: settings test variant 1
    contacts: contacts tests
    contacts_1: contacts test variant 1
    contact_2: contact update test
    leads: leads tests
    lead_1: lead test variant 1
    lead_2: lead update test
    company: company tests
    company_1: company test variant 1
    company_2: company update test
    deal: deal tests
    deal_1: deal test variant 1
    deal_2: deal update test
    contact_3: contact details page edit test
    lead_3: lead details page edit test
    company_3: company details page edit test
    deal_3: deal details page edit test
    not_automated: tests not yet automated
