[pytest]
addopts = --tb=short -q
log_cli = true
log_cli_level = WARNING
log_cli_format = %(message)s
log_level = WARNING
filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
    ignore::pytest.PytestWarning

markers =
    signIn: sign in tests
    signIn_1: sign in test variant 1
    signIn_2: sign in test variant 2
    settings: settings tests
    settings_1: settings test variant 1
    contacts: contacts tests
    contacts_1: contacts test variant 1
    leads: leads tests
    leads_1: leads test variant 1
    not_automated: tests not yet automated
